<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{28c6f53e-9ffe-4339-a37a-f92f28e532a1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
IN_TEST_1 AT%I* : BOOL;
		
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="134" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>